"""
LLM Client Services Module
==========================
This module acts as the universal adapter for all Large Language Model communications.
It abstracts the complexities of streaming (Server-Sent Events), payload formatting,
and network resilience (exponential backoff) away from the main API router.

Supports:
- Local SLMs (Ollama)
- Cloud LLMs (OpenAI, Google Gemini)
- Testing endpoints (Groq for ultra-fast local SLM simulation)
"""

import os
import json
import logging
import asyncio
import httpx
from openai import AsyncOpenAI
from dotenv import load_dotenv
from src.core.config import settings

# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)

# ==========================================
# ⚙️ DEVELOPMENT TOGGLES
# ==========================================
# Set to True to use high-speed cloud endpoints for testing to save time.
# Set to False to revert to your original local Ollama and OpenAI setup.
USE_FAST_TESTING_SLM = True  # Routes local calls to Groq
USE_GEMINI_CLOUD = True      # Routes cloud calls to Gemini

# ==========================================
# 🔌 CLIENT INITIALIZATION
# ==========================================
# Initialize the standard OpenAI asynchronous client
openai_client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

# Groq utilizes an OpenAI-compatible API schema. By pointing the OpenAI SDK 
# at the Groq base URL, we can use standard OpenAI methods to call Groq models.
groq_client = AsyncOpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)


async def call_local_llm_stream(messages: list[dict], max_retries: int = 3):
    """
    Streams the response from the Local SLM (or Groq during testing).
    
    Resilience Strategy:
    Implements stateful exponential backoff. If the local server is overloaded
    and drops the connection, it waits and retries. If the stream fails *during* 
    generation, it yields a specific JSON dictionary so the frontend knows to 
    abort the chat bubble and show an error Toast.

    Args:
        messages (list[dict]): The sanitized conversation history and system prompts.
        max_retries (int): Maximum number of connection attempts before failing.

    Yields:
        str: Raw text chunks as they are generated by the model.
        dict: An error dictionary `{"error": "message"}` if a fatal failure occurs.
    """
    # Ensure messages are strictly dicts to avoid Pydantic serialization issues
    clean_messages = [{"role": m["role"], "content": m["content"]} for m in messages]
    
    attempt = 0
    delay = 1.0

    while attempt < max_retries:
        yielded_any = False # Tracks if we have successfully sent at least one chunk to the user
        
        try:
            if USE_FAST_TESTING_SLM:
                # --- GROQ TESTING LOGIC ---
                logger.info(f"Routing to Fast Testing SLM (Attempt {attempt + 1}/{max_retries})...")
                response = await groq_client.chat.completions.create(
                    model="gemma2-9b-it", # Groq model identifier
                    messages=clean_messages,
                    temperature=0.7,
                    max_tokens=4096,
                    stream=True 
                )
                
                async for chunk in response:
                    content = chunk.choices[0].delta.content
                    if content:
                        yielded_any = True
                        yield content
                        # Artificial delay to drip-feed tokens, mimicking slower local SLM hardware
                        await asyncio.sleep(0.02)
                
                return  # Exit the generator completely on successful stream completion
                
            else:
                # --- ORIGINAL OLLAMA LOGIC ---
                logger.info(f"Routing to Local SLM ({settings.LOCAL_MODEL_NAME}) (Attempt {attempt + 1})...")
                url = f"{settings.OLLAMA_BASE_URL}/api/chat"
                payload = {"model": settings.LOCAL_MODEL_NAME, "messages": clean_messages, "stream": True}
                
                # Context manager ensures the HTTP connection is closed even if an error occurs
                async with httpx.AsyncClient(timeout=180.0) as client:
                    async with client.stream("POST", url, json=payload) as response:
                        response.raise_for_status()
                        async for line in response.aiter_lines():
                            if line:
                                data = json.loads(line)
                                if "message" in data and "content" in data["message"]:
                                    yielded_any = True
                                    yield data["message"]["content"]
                                    
                return  # Exit the generator completely on successful stream completion

        except Exception as e:
            attempt += 1
            logger.warning(f"SLM Stream Error (Attempt {attempt}): {str(e)}")
            
            # If we already sent text to the screen, we cannot seamlessly retry. 
            # We must notify the frontend to halt generation and show a Toast.
            if yielded_any:
                logger.error("Stream dropped mid-generation.")
                yield {"error": f"The generation was interrupted. ({str(e)})"}
                return
                
            # If all attempts fail before generating anything, notify the frontend.
            if attempt >= max_retries:
                logger.error("Max retries exhausted for SLM.")
                yield {"error": f"Local SLM failed after {max_retries} attempts. ({str(e)})"}
                return
                
            # Exponential Backoff (Wait 1s, then 2s, then 4s...)
            await asyncio.sleep(delay)
            delay *= 2


async def call_cloud_llm_stream(messages: list[dict], max_retries: int = 3):
    """
    Streams the response from the designated Cloud LLM (Gemini or OpenAI).
    Translates standard OpenAI-style message schemas into Gemini's proprietary schema if needed.

    Args:
        messages (list[dict]): The sanitized conversation history and system prompts.
        max_retries (int): Maximum number of connection attempts before failing.

    Yields:
        str: Raw text chunks as they are generated by the model.
        dict: An error dictionary `{"error": "message"}` if a fatal failure occurs.
    """
    attempt = 0
    delay = 1.0

    while attempt < max_retries:
        yielded_any = False
        
        try:
            if USE_GEMINI_CLOUD:
                # --- GOOGLE GEMINI LOGIC ---
                model_name = "gemini-1.5-flash" 
                logger.info(f"Routing to Cloud LLM (Gemini - {model_name}) (Attempt {attempt + 1}/{max_retries})...")
                api_key = os.getenv("GEMINI_API_KEY")
                
                # Gemini requires `alt=sse` to return standard Server-Sent Events
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:streamGenerateContent?key={api_key}&alt=sse"
                
                gemini_contents = []
                system_instruction = None
                
                # Schema Translation: OpenAI uses "system", "user", "assistant".
                # Gemini uses "systemInstruction" (separate) and "user", "model" (for history).
                for m in messages:
                    if m["role"] == "system":
                        system_instruction = {"parts": [{"text": m["content"]}]}
                    else:
                        role = "model" if m["role"] == "assistant" else "user"
                        gemini_contents.append({"role": role, "parts": [{"text": m["content"]}]})
                        
                payload = {"contents": gemini_contents}
                if system_instruction:
                    payload["systemInstruction"] = system_instruction

                async with httpx.AsyncClient(timeout=60.0) as client:
                    async with client.stream("POST", url, json=payload) as response:
                        response.raise_for_status()
                        async for line in response.aiter_lines():
                            if line.startswith("data: "):
                                data_str = line[6:]
                                if data_str.strip() == "[DONE]": 
                                    continue
                                
                                try:
                                    data = json.loads(data_str)
                                    # Safely navigate Gemini's deeply nested response dictionary
                                    candidates = data.get("candidates", [])
                                    if candidates and "content" in candidates[0]:
                                        parts = candidates[0]["content"].get("parts", [])
                                        if parts and "text" in parts[0]:
                                            content = parts[0]["text"]
                                            if content:
                                                yielded_any = True
                                                yield content
                                except json.JSONDecodeError:
                                    pass # Silently ignore partial JSON chunks during the active stream
                                    
                return  # Exit function completely on successful stream completion
                
            else:
                # --- ORIGINAL OPENAI LOGIC ---
                logger.info(f"Routing to Cloud LLM (OpenAI) (Attempt {attempt + 1}/{max_retries})...")
                clean_messages = [{"role": m["role"], "content": m["content"]} for m in messages]
                
                response = await openai_client.chat.completions.create(
                    model=settings.OPENAI_MODEL,
                    messages=clean_messages,
                    temperature=0.7,
                    max_tokens=4096,
                    stream=True
                )
                async for chunk in response:
                    content = chunk.choices[0].delta.content
                    if content:
                        yielded_any = True
                        yield content
                        
                return  # Exit function completely on successful stream completion

        except Exception as e:
            attempt += 1
            logger.warning(f"Cloud LLM Stream Error (Attempt {attempt}): {str(e)}")
            
            # Mid-stream failure handling
            if yielded_any:
                logger.error("Cloud stream dropped mid-generation.")
                yield {"error": f"The cloud generation was interrupted. ({str(e)})"}
                return
                
            # Exhausted retries handling
            if attempt >= max_retries:
                logger.error("Max retries exhausted for Cloud LLM.")
                yield {"error": f"Cloud LLM failed after {max_retries} attempts. ({str(e)})"}
                return
                
            # Exponential Backoff
            await asyncio.sleep(delay)
            delay *= 2